### ISSUE TITLE
"Port" attribute has a default value which is contrary to it being optional

### ISSUE THREAD

**Issue by akshay8043** [tmknight/TMK-CoreModules#2]
Hello Travis,

I liked your Start-Fastping PowerShell module and tested it in my environment.

And I wanted to try to perform a ping+port check on bulk servers.
So I built a basic supportive script.

But when I tried your script with an unknown server, I received the below results.
Port Status for failed servers shows "TRUE". which is incorrect as per logic.

**$serverlist = gc "D:\script\hosts.txt"
Import-Module "D:\script\Modified Start-fastping.ps1" -Force
foreach ($servers in $serverlist) 
{
Start-FastPing -ComputerName $servers -Port 3389 
}**

PS D:\script> Start-FastPing -ComputerName servernotexist.cloudservers.com -Port 3389

Your Script is perfect for perfect cases. But I had received a request to perform bulk operations and ended up noticing this issue.
Many times server list contains space or unknown characters shared by any human/analyst who might have generated manually. 

ComputerName   : servernotexist.cloudservers.com
HostName       : N/A
PingSucceeded  : False
A              : N/A
AAAA           : N/A
Port 3389 Open : **True**

**Script Description says:**
    $Port = 445
 .PARAMETER Lookup
	This parameter is optional.  If invoked, there are no values, it is a switch to true

So wanted to know if this is going to be like this forever, or is there anyway, that you can modify the script and use IF/ELSE in this to get the appropriate result. 
So it's just my opinion wanted to see if you may resolve this by any chance otherwise your script is perfect.

I believe the output of the script should be 
ComputerName   : servernotexist.cloudservers.com
HostName       : N/A
PingSucceeded  : False
A              : N/A
AAAA           : N/A
**Port 3389 Open : False**

**Comment by tmknight** [comment]
Good call-out.  Corrected.  Test and updates results here.
